# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='backend.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rbackend.proto\")\n\x07Profile\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nproperties\x18\x02 \x01(\t\"F\n\x0bMatchObject\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nproperties\x18\x02 \x01(\t\x12\x17\n\x06roster\x18\x03 \x01(\x0b\x32\x07.Roster\"(\n\x06Result\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x1c\n\x06Roster\x12\x12\n\nplayer_ids\x18\x01 \x01(\t\"+\n\x0e\x43onnectionInfo\x12\x19\n\x11\x63onnection_string\x18\x01 \x01(\t\"P\n\x0b\x41ssignments\x12\x17\n\x06roster\x18\x01 \x01(\x0b\x32\x07.Roster\x12(\n\x0f\x63onnection_info\x18\x02 \x01(\x0b\x32\x0f.ConnectionInfo2\xd8\x01\n\x03\x41PI\x12\'\n\x0b\x43reateMatch\x12\x08.Profile\x1a\x0c.MatchObject\"\x00\x12)\n\x0bListMatches\x12\x08.Profile\x1a\x0c.MatchObject\"\x00\x30\x01\x12&\n\x0b\x44\x65leteMatch\x12\x0c.MatchObject\x1a\x07.Result\"\x00\x12,\n\x11\x43reateAssignments\x12\x0c.Assignments\x1a\x07.Result\"\x00\x12\'\n\x11\x44\x65leteAssignments\x12\x07.Roster\x1a\x07.Result\"\x00\x62\x06proto3')
)




_PROFILE = _descriptor.Descriptor(
  name='Profile',
  full_name='Profile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Profile.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='Profile.properties', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=58,
)


_MATCHOBJECT = _descriptor.Descriptor(
  name='MatchObject',
  full_name='MatchObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MatchObject.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='MatchObject.properties', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roster', full_name='MatchObject.roster', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=130,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='Result.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='Result.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=172,
)


_ROSTER = _descriptor.Descriptor(
  name='Roster',
  full_name='Roster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_ids', full_name='Roster.player_ids', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=202,
)


_CONNECTIONINFO = _descriptor.Descriptor(
  name='ConnectionInfo',
  full_name='ConnectionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connection_string', full_name='ConnectionInfo.connection_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=247,
)


_ASSIGNMENTS = _descriptor.Descriptor(
  name='Assignments',
  full_name='Assignments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roster', full_name='Assignments.roster', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connection_info', full_name='Assignments.connection_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=329,
)

_MATCHOBJECT.fields_by_name['roster'].message_type = _ROSTER
_ASSIGNMENTS.fields_by_name['roster'].message_type = _ROSTER
_ASSIGNMENTS.fields_by_name['connection_info'].message_type = _CONNECTIONINFO
DESCRIPTOR.message_types_by_name['Profile'] = _PROFILE
DESCRIPTOR.message_types_by_name['MatchObject'] = _MATCHOBJECT
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['Roster'] = _ROSTER
DESCRIPTOR.message_types_by_name['ConnectionInfo'] = _CONNECTIONINFO
DESCRIPTOR.message_types_by_name['Assignments'] = _ASSIGNMENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Profile = _reflection.GeneratedProtocolMessageType('Profile', (_message.Message,), dict(
  DESCRIPTOR = _PROFILE,
  __module__ = 'backend_pb2'
  # @@protoc_insertion_point(class_scope:Profile)
  ))
_sym_db.RegisterMessage(Profile)

MatchObject = _reflection.GeneratedProtocolMessageType('MatchObject', (_message.Message,), dict(
  DESCRIPTOR = _MATCHOBJECT,
  __module__ = 'backend_pb2'
  # @@protoc_insertion_point(class_scope:MatchObject)
  ))
_sym_db.RegisterMessage(MatchObject)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'backend_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  ))
_sym_db.RegisterMessage(Result)

Roster = _reflection.GeneratedProtocolMessageType('Roster', (_message.Message,), dict(
  DESCRIPTOR = _ROSTER,
  __module__ = 'backend_pb2'
  # @@protoc_insertion_point(class_scope:Roster)
  ))
_sym_db.RegisterMessage(Roster)

ConnectionInfo = _reflection.GeneratedProtocolMessageType('ConnectionInfo', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIONINFO,
  __module__ = 'backend_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionInfo)
  ))
_sym_db.RegisterMessage(ConnectionInfo)

Assignments = _reflection.GeneratedProtocolMessageType('Assignments', (_message.Message,), dict(
  DESCRIPTOR = _ASSIGNMENTS,
  __module__ = 'backend_pb2'
  # @@protoc_insertion_point(class_scope:Assignments)
  ))
_sym_db.RegisterMessage(Assignments)



_API = _descriptor.ServiceDescriptor(
  name='API',
  full_name='API',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=332,
  serialized_end=548,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateMatch',
    full_name='API.CreateMatch',
    index=0,
    containing_service=None,
    input_type=_PROFILE,
    output_type=_MATCHOBJECT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListMatches',
    full_name='API.ListMatches',
    index=1,
    containing_service=None,
    input_type=_PROFILE,
    output_type=_MATCHOBJECT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteMatch',
    full_name='API.DeleteMatch',
    index=2,
    containing_service=None,
    input_type=_MATCHOBJECT,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateAssignments',
    full_name='API.CreateAssignments',
    index=3,
    containing_service=None,
    input_type=_ASSIGNMENTS,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteAssignments',
    full_name='API.DeleteAssignments',
    index=4,
    containing_service=None,
    input_type=_ROSTER,
    output_type=_RESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_API)

DESCRIPTOR.services_by_name['API'] = _API

# @@protoc_insertion_point(module_scope)
