# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import backend_pb2 as backend__pb2


class APIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateMatch = channel.unary_unary(
        '/API/CreateMatch',
        request_serializer=backend__pb2.Profile.SerializeToString,
        response_deserializer=backend__pb2.MatchObject.FromString,
        )
    self.ListMatches = channel.unary_stream(
        '/API/ListMatches',
        request_serializer=backend__pb2.Profile.SerializeToString,
        response_deserializer=backend__pb2.MatchObject.FromString,
        )
    self.DeleteMatch = channel.unary_unary(
        '/API/DeleteMatch',
        request_serializer=backend__pb2.MatchObject.SerializeToString,
        response_deserializer=backend__pb2.Result.FromString,
        )
    self.CreateAssignments = channel.unary_unary(
        '/API/CreateAssignments',
        request_serializer=backend__pb2.Assignments.SerializeToString,
        response_deserializer=backend__pb2.Result.FromString,
        )
    self.DeleteAssignments = channel.unary_unary(
        '/API/DeleteAssignments',
        request_serializer=backend__pb2.Roster.SerializeToString,
        response_deserializer=backend__pb2.Result.FromString,
        )


class APIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateMatch(self, request, context):
    """Calls to ask the matchmaker to run a matchmaking function.

    Run MMF once.  Return a matchobject that fits this profile.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListMatches(self, request, context):
    """Continually run MMF and stream matchobjects that fit this profile until
    client closes the connection.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteMatch(self, request, context):
    """Delete a matchobject from state storage manually. (Matchobjects in state
    storage will also automatically expire after a while)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateAssignments(self, request, context):
    """Call that manage communication of  DGS connection info to players. 

    Write the DGS connection info for the list of players in the
    Assignments.roster to state storage, so that info can be read by the game
    client(s).
    TODO: change this to be agnostic; return a 'result' instead of a connection
    string so it can be integrated with session service etc
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteAssignments(self, request, context):
    """Remove DGS connection info for the list of players in the Roster from
    state storage.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_APIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateMatch': grpc.unary_unary_rpc_method_handler(
          servicer.CreateMatch,
          request_deserializer=backend__pb2.Profile.FromString,
          response_serializer=backend__pb2.MatchObject.SerializeToString,
      ),
      'ListMatches': grpc.unary_stream_rpc_method_handler(
          servicer.ListMatches,
          request_deserializer=backend__pb2.Profile.FromString,
          response_serializer=backend__pb2.MatchObject.SerializeToString,
      ),
      'DeleteMatch': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteMatch,
          request_deserializer=backend__pb2.MatchObject.FromString,
          response_serializer=backend__pb2.Result.SerializeToString,
      ),
      'CreateAssignments': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAssignments,
          request_deserializer=backend__pb2.Assignments.FromString,
          response_serializer=backend__pb2.Result.SerializeToString,
      ),
      'DeleteAssignments': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteAssignments,
          request_deserializer=backend__pb2.Roster.FromString,
          response_serializer=backend__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'API', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
