# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import frontend_pb2 as frontend__pb2


class APIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateRequest = channel.unary_unary(
        '/API/CreateRequest',
        request_serializer=frontend__pb2.Group.SerializeToString,
        response_deserializer=frontend__pb2.Result.FromString,
        )
    self.DeleteRequest = channel.unary_unary(
        '/API/DeleteRequest',
        request_serializer=frontend__pb2.Group.SerializeToString,
        response_deserializer=frontend__pb2.Result.FromString,
        )
    self.GetAssignment = channel.unary_unary(
        '/API/GetAssignment',
        request_serializer=frontend__pb2.PlayerId.SerializeToString,
        response_deserializer=frontend__pb2.ConnectionInfo.FromString,
        )
    self.DeleteAssignment = channel.unary_unary(
        '/API/DeleteAssignment',
        request_serializer=frontend__pb2.PlayerId.SerializeToString,
        response_deserializer=frontend__pb2.Result.FromString,
        )


class APIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAssignment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteAssignment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_APIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateRequest': grpc.unary_unary_rpc_method_handler(
          servicer.CreateRequest,
          request_deserializer=frontend__pb2.Group.FromString,
          response_serializer=frontend__pb2.Result.SerializeToString,
      ),
      'DeleteRequest': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteRequest,
          request_deserializer=frontend__pb2.Group.FromString,
          response_serializer=frontend__pb2.Result.SerializeToString,
      ),
      'GetAssignment': grpc.unary_unary_rpc_method_handler(
          servicer.GetAssignment,
          request_deserializer=frontend__pb2.PlayerId.FromString,
          response_serializer=frontend__pb2.ConnectionInfo.SerializeToString,
      ),
      'DeleteAssignment': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteAssignment,
          request_deserializer=frontend__pb2.PlayerId.FromString,
          response_serializer=frontend__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'API', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
